CREATE USER 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd';
-- CREATE USER 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd';

-- CREATE DATABASE IF NOT EXISTS s3_management;
CREATE DATABASE s3_management;
GRANT ALL PRIVILEGES ON `s3_management`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_management`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;

CREATE DATABASE s3_auths;
GRANT ALL PRIVILEGES ON `s3_auths`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_auths`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_cdets;
GRANT ALL PRIVILEGES ON `s3_cdets`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_cdets`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;


CREATE DATABASE s3_communications;
GRANT ALL PRIVILEGES ON `s3_communications`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_communications`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_controller;
GRANT ALL PRIVILEGES ON `s3_controller`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_controller`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_genie;
GRANT ALL PRIVILEGES ON `s3_genie`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_genie`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_groups;
GRANT ALL PRIVILEGES ON `s3_groups`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_groups`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_history;
GRANT ALL PRIVILEGES ON `s3_history`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_history`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_jenkinsengine;
GRANT ALL PRIVILEGES ON `s3_jenkinsengine`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_jenkinsengine`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_laas;
GRANT ALL PRIVILEGES ON `s3_laas`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_laas`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_labvpn;
GRANT ALL PRIVILEGES ON `s3_labvpn`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_labvpn`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_monitors;
GRANT ALL PRIVILEGES ON `s3_monitors`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_monitors`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_plugins;
GRANT ALL PRIVILEGES ON `s3_plugins`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_plugins`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_qmgr;
GRANT ALL PRIVILEGES ON `s3_qmgr`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_qmgr`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_registry;
GRANT ALL PRIVILEGES ON `s3_registry`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_registry`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_requests;
GRANT ALL PRIVILEGES ON `s3_requests`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_requests`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_resources;
GRANT ALL PRIVILEGES ON `s3_resources`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_resources`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_results;
GRANT ALL PRIVILEGES ON `s3_results`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_results`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_sessions;
GRANT ALL PRIVILEGES ON `s3_sessions`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_sessions`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_testbeds;
GRANT ALL PRIVILEGES ON `s3_testbeds`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_testbeds`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_topoman;
GRANT ALL PRIVILEGES ON `s3_topoman`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_topoman`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;



CREATE DATABASE s3_users;
GRANT ALL PRIVILEGES ON `s3_users`.* TO 's3_admin'@'localhost' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `s3_users`.* TO 's3_admin'@'192.168.66.%' IDENTIFIED BY 's3_PaSsW0Rd' WITH GRANT OPTION;
